Fix build errors
We must resolve `@types/node` to a specific version because tslint
(which is old) brings in a version of `@types/node` that does not work.
We get these errors:

    node_modules/@types/node/ts4.8/test.d.ts:698:76 - error TS1005: ',' expected.

    698         target: F extends abstract new(...args: any) => any ? F : undefined;
                                                                                  ~
    node_modules/@types/node/ts4.8/test.d.ts:702:22 - error TS1005: ',' expected.

    702         this: unknown;

The long-term fix is to migrate from TSLint to ESLint and then use a
more recent version of Typescript.